#include <stdio.h>
#include <dlfcn.h>
#include <unistd.h>
#include <stdlib.h>
#include <wait.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/stat.h> 
#include <string.h>
#include <fcntl.h>
